export const UPDATE_REGION = 'UPDATE_REGION';

export const NEW_DICES = 'NEW_DICES';
export const ROLL_DICES = 'ROLL_DICES';
export const UPDATE_POSITION_DICES = 'UPDATE_POSITION_DICES';
export const REST_POSITION_DICES = 'REST_POSITION_DICES';

export const CHANGED_TABLE = 'CHANGED_TABLE';
export const UPDATE_TABLE = 'UPDATE_TABLE';
